//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Assets.Scripts.Utilities.Messaging;
using Assets.Scripts.Weapons.Interfaces;
using Assets.Scripts.Character.Interfaces;
using Assets.Scripts.Utilities.Messaging.Interfaces;
using UnityEngine;

namespace Assets.Scripts.Weapons.Bases
{
	public class MeleeWeaponBase : IMeleeWeapon
	{
		
		public Vector3 Position { get; set; }
			
		private IReceiver receiver;
		public IReceiver Receiver { set {this.Receiver = value;} }

		private IMessageDispatcher messageDispatcher;
		public MeleeWeaponBase()
		{
			
		}

		public MeleeWeaponBase(IReceiver receiver, IMessageDispatcher messageDispatcher)
		{
			this.receiver = receiver;
			this.receiver.Owner = this;
			this.messageDispatcher = messageDispatcher;

			receiver.SubScribe();
		}

		public void PickUp(ICharacter character)
		{
			messageDispatcher.DispatchMessage(new Telegram(character, this));
		}

		public int Attack()
		{
			return 10;
		}

		public void Receive(ITelegram telegram)
		{

		}
	}
}

