//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Assets.Scripts.Weapons.Interfaces;
using Assets.Scripts.Character.Interfaces;
using Assets.Scripts.Utilities.Messaging.Interfaces;
using UnityEngine;

namespace AssemblyCSharp
{
		public class MeleeWeaponBase : IMeleeWeapon
		{

			public Vector3 Position { get; set; }
			
		private IReceiver receiver;
			public IReceiver Receiver { set {this.Receiver = value;} }
			public void PickUp(ICharacter character)
			{

			}

			public void Attack()
			{

			}

			public void Receive(ITelegram telegram)
			{

			}
		}
}

